language: ruby
rvm:
- 2.2.1
branches:
  only:
  - develop
script: rake travis
env:
  global:
  - secure: KoKbBw0U6sOD6c0Y8RbGM95gkq0klHsD69TraERKmKB51dwSaPOxL1fg7halkCXkKOSpIdczzVvY5hZ3A0NFV0C0IGjROmMY0rNOqRHnBknsbw/YF8UR6p8N9OAFEdE5FJ8E/b0olzOzE9fegBhvCmvQaJAkkLsJayy+KaPUtyU=
  - secure: ZgL4kw8ApipPimMcU2FCAs7pDyDSJi2jnE4Bm5QoyGGly9FX6RSRPYcvzJ+Hym0T6qz0tBKRUe+wygxEOFe36SAc9tUwzNxDwNW/K1IiqEy6JxfOUmy3fsbQWQIRhA16fsZf2Vsn7VU206fP5UuKz49YLonWmXaGQtArETvCqPA=
