name: goldstift
author: Alexander Heusingfeld
title: goldstift's blog
heading: goldstift's 2 cent on technology and software development
blog_path: /posts
base_url: ''
local_tz: Europe/Berlin
interpolate: false
disqus: goldstift
disqus_generate_id: false
disqus_developer: true
haml:
  :ugly: true

asciidoctor:
  :safe: unsafe
  :base_dir: null
  :compact: true
  :attributes:
    idprefix: ''
    idseparator: '-'
    icons: font

profiles:
  development:
    minify: false
    disqus_developer: true
    dev: true
    deploy: nil
  staging:
    deploy: nil
  production:
    base_url: http://aheusingfeld.github.io
    disqus_developer: false
    scss:
      :line_numbers: false
      :style: :compressed
    #compass_output_style: :compressed
    minify: true
    deploy:
      host: github_pages
      branch: master  
